#
#
#   Licensed to the Apache Software Foundation (ASF) under one or more
#   contributor license agreements.  See the NOTICE file distributed with
#   this work for additional information regarding copyright ownership.
#   The ASF licenses this file to You under the Apache License, Version 2.0
#   (the "License"); you may not use this file except in compliance with
#   the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#

dubbo.application.name=kubernetes-apiserver-demo-consumer
dubbo.application.metadataServicePort=20885
dubbo.registry.address=kubernetes://kubernetes.docker.internal:6443?registry-type=service&duplicate=false&namespace=dubbo-demo&trustCerts=true&oauthToken=eyJhbGciOiJSUzI1NiIsImtpZCI6ImxhT0c4cU1WUXpYSE1iYk5lTHZLT0Rfa2pjV3BwcjBzS2U3ci1jWnJfMEEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkdWJiby1kZW1vIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImR1YmJvLXNhLXRva2VuLTR3ajRmIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImR1YmJvLXNhIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMWM5ZmRmNGMtZjFmNS00ODJmLThjZGYtZDZhYzk0ZTNmYzFiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmR1YmJvLWRlbW86ZHViYm8tc2EifQ.Hf3TwCX446HBW3C3nujlp6cGVkqTglTE653Ix1ttarAf9zv7luJibP4YQZow0lKnCEpn2iLioitTYrH33yjMIUPwaMY0vRgELs940U0yQ4vZ3zccag3TTeoCqAjoiRNK0g8N-5gM4lYOm8USifTCAsTkNtzKpf9GBVP1NyJGeaOXna3ulj85Xw7TgAy-Bi38odp1WkzHd_e4Js3nvlsKOtHeHenmRepALDShIgDZWGeYXWFYLdijWHqjQka_JCdEC-23VnS5n4zidF05-Tx7YXzJFZZ4z5Uj-TA8DHehBxqwaTbKKpJgIq7EAFmcWD7P1KRN5g663gmfOc3p-GrYEw
dubbo.consumer.timeout=3000
dubbo.application.qosEnable=true
dubbo.application.qosAcceptForeignIp=true